spring:
  config:
    name: marketing-platform-app
  profiles:
    active: dev

# logging.pattern.console: '%clr([%d{yyyy-MM-dd HH:mm:ss.SSS}]){faint} %clr(-){faint} %clr(%p) %clr(-){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'